on: [push, pull_request]
name: Build/Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Test access point
      run: go test ./...
    - name: Test robot radio
      run: go test -tags robot ./...
    - name: Check formatting
      run: test -z "$(go fmt ./...)"
